Remove broken multishop support
PrestaShop/blockreassurance pull request #336
Opened 2022-01-12 12:21 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The multishop support of this module was never really working and this fix on the `ObjectModel` made it break even more, leading to an exception. This PR solve the issue by disabling multishop support.
| Type?         | bug fix
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | PrestaShop/PrestaShop#26991, PrestaShop/PrestaShop#26979, PrestaShop/PrestaShop#26980, PrestaShop/PrestaShop#26531 
| How to test?  | Please see related issues

### BC Break
Method `ReassuranceActivity::getAllBlockByLang` has been removed
Method `ReassuranceActivity::getAllBlockByShop` has been removed
The second parameter of the method `ReassuranceActivity::getAllBlockByStatus` has been removed (`$id_shop`)

2022-01-12 12:58 UTC, matks reviewed
If we disable multishop support we need to inform people in the README https://github.com/PrestaShop/blockreassurance/blob/dev/README.md

2022-01-12 12:58 UTC, matks commented on blockreassurance.php
> +            PRIMARY KEY (`id_psreassurance`,`id_lang`)
If we put back the mutishop support later maybe we can keep the SQL structure?

2022-01-13 09:39 UTC, MatShir commented
> Please give me 1-2 days, I will check how much time would be needed to make it compatible. I will let you know if I can do it. I think it's better to have it working instead of removing it.

The blockreassurance is poorly design for the multistore. Only editing the content of the field text was working, you can't disable/enable an item for a specific context, you can't change the displayed or images. So the configuration part for a specific shop is not working. So I prefer that we assume that the module is not multistore compatible for the configuration rather than do it poorly and do it properly in a second time. 
@kpodemski this PR fixes a lot of major bug. Maybe we can add the multistore compat in another one to avoid to many side effects during test it. WDYT ?

2022-01-13 09:51 UTC, kpodemski commented
@MatShir 

Ok

2022-02-21 09:20 UTC, atomiix commented
@kpodemski If I remember well, you were willing to add full multishop support to this module, is it still something you plan to do?

2022-03-04 09:56 UTC, matthieu-rolland reviewed
LGTM, but the PR needs a rebase and there seems to be a few js lint issues 👍

2022-03-14 20:56 UTC, PierreRambaud approved these changes

2022-03-20 12:41 UTC, kpodemski commented
@atomiix 

Yes, it's something I want to do in Q2 with a refacto of the module, so it would be a bigger project

2022-03-22 16:16 UTC, HanaRebaiQA requested changes
Hello @atomiix 

I have tested this PR. I found theses issues which are related to this PR : 

_**Check with develop (using the module from dev branch)**_  

**Issue 1 : There is not the possibility to add a new block (A 500 error)** 

1. BO > IMPROVE > Module Manager > blockreassurance > Configure
2. Click on the + icon to add a new Block content
3. Add a new image 
5. See error >> A 500 error is thrown for the first time and there is not the possibility to Save 

![image](https://user-images.githubusercontent.com/92912932/159524699-aaca7c55-19fa-4ed9-9107-aad81f796823.png)

https://user-images.githubusercontent.com/92912932/159525552-797ee6b4-feee-4956-ba35-6ee34ed4a264.mp4

_**Check with PS1785 (using the module from dev branch)**_  

**Issue 2.  ​All blocks for each shop configured are displayed toghether for every shop in BO & FO**

1. BO > IMPROVE > Module Manager > blockreassurance > Configure
2. Enable multistore and add different shops and group of shops
3. Add a new block with `+` icon for each shop (new shop created, default shop etc)
4. Select a shop
5. See error >> The other blocks already created for the other shops are displayed in the current one (in BO)
![image](https://user-images.githubusercontent.com/92912932/159526206-48dafaa1-0cf0-4a0f-b993-b0f19b4ac352.png)

6. Click on view my shop
7. See error >> The other blocks already created for the other shops are displayed in the current one (in FO)
![image](https://user-images.githubusercontent.com/92912932/159521319-7bc8e206-c3dd-4daa-80bb-e3f8b39c6fd9.png)

_With PR_

https://user-images.githubusercontent.com/92912932/159520438-ee9526bc-299c-44a4-bf75-4174c24a1514.mp4

_Without PR_ 

https://user-images.githubusercontent.com/92912932/159520903-47a94543-a1cb-4a08-827d-41b8eee6e00d.mp4



**Issue 3. The image icon is not dispayed in BO & FO when adding a new block**

1. BO > IMPROVE > Module Manager > blockreassurance > Configure
3. Add a new block with `+` icon 
4. Add an image for the block and Save
7. See error >> The image icon for the added block is not displayed (In BO)
8. Click on view my shop
9. See error >> The image icon for the added block is not displayed (In FO)

![image](https://user-images.githubusercontent.com/92912932/159526368-233f42b7-0c80-464c-a444-eb70af851e2c.png)


_With PR_

https://user-images.githubusercontent.com/92912932/159521855-8b5a7cea-bd77-481e-8549-f4f2843fdc52.mp4

_Without PR_

https://user-images.githubusercontent.com/92912932/159522038-05f5e0d4-01f0-4b65-9105-635e3c34b879.mp4



**Issue 4. I was able to reproduce this issue [#26531](https://github.com/PrestaShop/PrestaShop/issues/26531) again using theses steps** 

1. BO > IMPROVE > Module Manager > blockreassurance > Configure
3. Add a new block with `+` icon 
4. Add all informations and Save
7. Click on edit of the created block
8. Update the language/Redirection type 
10. See error >> The error message `The field "Title" is required at least in your default language ` is displayed

![image](https://user-images.githubusercontent.com/92912932/159526472-4e8fb865-e7db-49db-be30-701de6ed3462.png)


https://user-images.githubusercontent.com/92912932/159525814-6b5ba66a-f8b2-46d1-ac8a-9fc67a97666f.mp4


Could you please check ?



Thanks!

2022-03-23 15:22 UTC, atomiix commented
hi @HanaRebaiQA, for all the bugs where the other blocks already created for the other shops are displayed in the current one, this is the expected behavior as this PR remove the multishop support. Whatever context you are, blocks are gonna be displayed in every shops.

For the others bugs, I don't understand, I tried on my side but I wasn't able to reproduce it. Can you have a look again?

Here is what I got:

https://user-images.githubusercontent.com/2168836/159734189-4a4de1ea-5a6c-4d48-9723-41909a4bfffe.mov

2022-03-24 17:21 UTC, HanaRebaiQA requested changes
Hello @atomiix 

Thank you for your feedback.
Yes, indeed it was a permission problem.

I have those new issues : 
**First issue : In develop branch** 
An error is displayed in FO when preview with the new shop created.


1. Enable multistore and create a new shop
2. BO > Module Manager > Blockreassurance
3. Configure the module with the new shop created
4. Create a block
5. Preview with the new shop in FO 
8. See error > An error is displayed in the whole page

![image](https://user-images.githubusercontent.com/92912932/160088416-b99045e1-9148-4d75-afbf-3215cbb4fbc0.png)

https://user-images.githubusercontent.com/92912932/159971682-4280cf55-51c4-4a34-94ab-a2f521f25391.mp4

**Second issue : In 1785 version** 
The image is not displayed with the new shop created in FO after editing the block 

1. Enable multistore and create a new shop
2. BO> Module Manager > Blockreassurance
3. Configure the module with the new shop created
4. Create a block
5. Preview with the new shop in FO 
6. Edit the block with another type (for example: change the Redirection `None` by `CMS Page`
7. Go to FO
8. See error > The image is not displayed again! 

_With PR_ 

https://user-images.githubusercontent.com/92912932/159972785-8d86fd36-b8fd-465d-b8ff-773904a17774.mp4

The type here is `svg`

_Without PR_
![image](https://user-images.githubusercontent.com/92912932/159973565-843756df-b800-45b6-8017-80fd06663ceb.png)

![image](https://user-images.githubusercontent.com/92912932/159973185-77248579-5189-4ac2-8c7c-42d2bffff782.png)

https://user-images.githubusercontent.com/92912932/159973047-28248450-bd6b-4f2c-bf5a-887f56c4474d.mp4


the type here is `svg invisible`

Im waiting for your feedback 

Thank you

2022-03-25 15:36 UTC, HanaRebaiQA approved these changes
Hello @atomiix 

I checked again this PR. Here is my last feedback : 

Check on PS1785 and develop branches : 
1. All issues are verified and fixed : OK 
2. Check with multistore : Ok
3. Check with different languages (RTL and no RTL) in BO & FO : OK
![image](https://user-images.githubusercontent.com/92912932/160151837-178ce5a3-9334-481c-895c-ed3a1db04851.png)
4. Check with different image types (svg, jpg, jpe, jpeg, png) : OK
5. Check with different combinations of block Display, Appearance, Content : OK 
6. Check with responsive : OK 
![image](https://user-images.githubusercontent.com/92912932/160152111-3f50c459-1779-4018-80ff-edc742e1b446.png)

7. Check with mobile : OK 
![image](https://user-images.githubusercontent.com/92912932/160152209-9ce0a36d-14a3-4d55-8078-346cffa52c6a.png)


https://user-images.githubusercontent.com/92912932/160151898-dc32a9b4-d121-4227-a6f0-68244a8a42c0.mp4


I found other issues but there are not related to this PR.

So, It's QA :heavy_check_mark: 

Thanks!

2022-03-25 15:43 UTC, merged

2022-03-25 15:43 UTC, Progi1984 commented
Thanks @atomiix & @HanaRebaiQA