Removed unuseful dependencies
PrestaShop/blockreassurance pull request #359
Opened 2022-02-14 15:33 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | After #219, some dependencies are not useful. After that, we can add blockreassurance to v8.0 (PrestaShop/PrestaShop/issues/27039)
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Relative to PrestaShop/PrestaShop/issues/27039
| How to test?  | Check if the module runs correctly.

2022-02-14 16:56 UTC, atomiix approved these changes

2022-02-15 09:44 UTC, PierreRambaud approved these changes

2022-02-15 12:19 UTC, NeOMakinG approved these changes

2022-02-17 09:14 UTC, florine2623 requested changes
Hello @Progi1984 ,

Thanks for the PR !

I have encountered 2 issues on this PR.

- I can't add a new reassurance block, I have an 500 error :

https://user-images.githubusercontent.com/16019289/154442886-f003b7c0-8a12-45b0-9311-fc48797290ea.mov

- I can't choose "Above footer" in Display > Footer position on all pages :
<img width="1140" alt="Screenshot 2022-02-17 at 10 13 51" src="https://user-images.githubusercontent.com/16019289/154443549-4955eb98-4edc-45c9-b355-57d6d6ddf114.png">

Could you check ?
Thanks!

2022-04-01 09:13 UTC, NeOMakinG approved these changes

2022-04-01 10:14 UTC, atomiix approved these changes

2022-04-04 05:58 UTC, PierreRambaud approved these changes

2022-04-07 13:19 UTC, florine2623 approved these changes
Hello @Progi1984 ,

Tested :
Content Tab
- Edited/Deleted existing blocks
- Activate/Deactivate blocks
- Added/Deleted/Edited new blocks
- Checked translations
- Added redirections to URL and CMS page

All Positions in Display Tab
Appearance Tab

Thanks, it is QA ✅

2022-04-07 13:22 UTC, merged

2022-04-07 13:22 UTC, Progi1984 commented
Thanks @florine2623