Different template based on hook name
PrestaShop/blockreassurance pull request #369
Opened 2022-03-01 18:41 UTC by Triloworld

`module:blockreassurance/views/templates/hook/blockreassurance.tpl` is hard-coded and for all hooks
Enable theming base on hook name for widgets.
Default get blockreassurance tpl for backward compatibility.
Pleas check my pull request for default theme scenario

2022-03-01 18:45 UTC, kpodemski commented
Hello @Triloworld 

Could you follow your contribution guidelines? You should fill out the default PR table.

2022-03-02 09:30 UTC, saulaski requested changes

2022-03-03 08:47 UTC, PierreRambaud commented on blockreassurance.php
> +        if($this->fetch('module:blockreassurance/views/templates/hook/' . $hookName . '.tpl') == null){
```suggestion
        if ($this->fetch('module:blockreassurance/views/templates/hook/' . $hookName . '.tpl') === null) {
```

2022-04-19 09:44 UTC, matks commented
Hello this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

Thank you @Triloworld

2022-04-19 14:38 UTC, Triloworld commented
Don't close. I work on it. Just need some more time. This is required in every update to be fixed by us in template so It is better to incorporate it into code.

2022-08-31 20:10 UTC, matks commented
@Triloworld I see you want to work on this but... I see no progress. I'm sorry 😞 I think you dont find the time to work on it

2022-09-29 15:10 UTC, matks commented
I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale.

Feel free to ping me to reopen 😉  or open another one if you think it's still relevant.

Thanks!

2022-09-29 15:10 UTC, closed without merging